name: Build ThinkFan for OpenWrt x86

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set Terminal Type
        run: export TERM=xterm
        
      - name: Install Build Dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext wget unzip python3
        
      - name: Download OpenWrt SDK
        run: |
          cd $GITHUB_WORKSPACE
          mkdir openwrt-sdk
          cd openwrt-sdk
          wget https://downloads.openwrt.org/releases/22.03.2/targets/x86/generic/openwrt-sdk-22.03.2-x86-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-22.03.2-x86-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          ./scripts/feeds update -a || true
          ./scripts/feeds install -a || true
          
      - name: Copy ThinkFan Package to SDK
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p openwrt-sdk/package/custom
          git clone https://github.com/vmatare/thinkfan.git openwrt-sdk/package/custom/thinkfan
        
      - name: Install ThinkFan Package Dependencies
        run: |
          cd $GITHUB_WORKSPACE/openwrt-sdk
          ./scripts/feeds install -p custom thinkfan
        
      - name: Compile ThinkFan Package
        run: |
          cd $GITHUB_WORKSPACE/openwrt-sdk
          make package/thinkfan/compile V=s
        
      - name: Upload IPK Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: thinkfan-ipk
          path: |
            bin/packages/x86/generic/thinkfan*.ipk
