name: Build and Publish OpenWrt mbpfan Package

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y --no-install-recommends build-essential git python3 unzip wget libncurses5-dev zlib1g-dev gawk flex gettext curl ca-certificates cmake-curses-gui libyaml-cpp-dev pkg-config libsensors-dev libconfuse-dev git-lfs
          git lfs install

      # Clone OpenWrt repository
      - name: Clone OpenWrt repository
        run: git clone https://git.openwrt.org/openwrt/openwrt.git openwrt

      # Configure OpenWrt
      - name: Configure OpenWrt
        run: cd openwrt && ./scripts/feeds update -a && ./scripts/feeds install -a

      # Add mbpfan package to OpenWrt
      - name: Add mbpfan package to OpenWrt
        run: cd openwrt/package/ && git clone https://github.com/linux-on-mac/mbpfan.git && ln -s ../../package/mbpfan package/

      # Build OpenWrt with mbpfan
      - name: Build OpenWrt with mbpfan
        run: |
          cd openwrt && \
          make defconfig && \
          sed -i 's/# CONFIG_PACKAGE_mbpfan is not set/CONFIG_PACKAGE_mbpfan=y/' .config && \
          make package/mbpfan/compile V=s TARGET=x86

      # Create a GitHub release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: OpenWrt mbpfan Package v1.0.0
          body: |
            Description of the release goes here.
          draft: false
          prerelease: false

      # Upload IPK file to the GitHub release
      - name: Upload Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openwrt/bin/targets/x86/generic/packages/mbpfan_*.ipk
          asset_name: mbpfan.ipk
          asset_content_type: application/octet-stream
