name: Build and Upload Pwm Package for OpenWrt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc wget python unzip

      - name: Update feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure
        run: |
          cd openwrt
          make defconfig
          make menuconfig
          sed -i 's/# CONFIG_PACKAGE_pwm is not set/CONFIG_PACKAGE_pwm=y/' .config

      - name: Compile package
        run: |
          cd openwrt/package
          ln -s ../../pwm .
          cd ..
          make package/pwm/compile V=s

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload pwm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: openwrt/bin/packages/*/base/pwm*.ipk
          asset_name: pwm.ipk
          asset_content_type: application/ipk
